### PR TITLE
Installer: Add check for supported Windows version

### PR DESCRIPTION
**Pull request by cher-nov**
This will help to prevent issues like [this (in Russian)](https://web.archive.org/web/20160906014201/http://stascorp.com/load/1-1-0-63#ent4377) in future.

### CODE REVIEW

**Comment by binarymaster** [comment]
Many thanks!

**Comment by Hurrican666** [comment]
Please Help Windows 10 pro NEW UPDATE 1803 today (04.05.2018) doesen´t work with RDP-Wrap...


any Ideas?

**Comment by Hurrican666** [comment]
Sorry can´t find Button to send you an PM … what did i do wrong ?

**Comment by kotterheidtdennis33-ux** [comment]
Okay danke

**Pull request merged**
