### PR TITLE
-->> RDP Wrapper & Autoupdate (07-06-2020)

### PR DESCRIPTION
**Pull request by asmtron**
# RDP Wrapper & Autoupdate

#### Info:
   The Autoupdater (autoupdate.bat) first use and check the official rdpwrap.ini.
   If a new termsrv.dll is not supported in the offical rdpwrap.ini,
   autoupdater first tries the asmtron rdpwrap.ini. The autoupdater will also use rdpwrap.ini files
   of other contributors. Extra rdpwrap.ini sources can also be defined...
   
#### autoupdate.bat Options:
- -log        = redirect display output to the file autoupdate.log
- -taskadd    = add autorun of autoupdate.bat on startup in schedule task
- -taskremove = remove autorun of autoupdate.bat on startup in schedule task

#### [Download and Install](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)

#
## NEWS
2020-12-06 -- add support for 10.0.19041.84 (x64)

### CODE REVIEW

**Comment by PrplHaz4** [comment]
Thanks for writing this up @asmtron and including a PR.  This seems to be a much safer way to distribute changes/updates to RDPwrap.  Much better than linking to some random site with precompiled binaries...etc.

As it stands, the issues here could easily be (already are?) a vector for malware distribution, as people tend to just click, download and run.

It really is a shame none of this work is getting merged into the repo - clearly there are lots of people dependent on this wrapper being functional.

@binarymaster any chance of adding @asmtron and/or @saurav-biswas as a maintainer on the repo?

**Comment by junkwes** [comment]
Listener state: Not listening

**Comment by asmtron** [comment]
### **Important -> autoupdate.bat _**bugfix!_**

1. **bug:** normal copy with admin right of the file "rdpwrap_new.ini" to "rdpwrap.ini" will not work properly (file locked)
2. **fix:** we need to stream the data line by line from "rdpwrap_new.ini" to "rdpwrap.ini"
3. **add:** listener check

**With this bugfix autoupdate.bat works now as expected...**

**Comment by ericernie** [comment]
asmtron-rdpwrap.ini-02.09.2019.zip should work for 18362.267 ? 
 that number is not a heading in the ini though..

**Comment by johnvondoe** [comment]
You, Sirs, have my deepest gratitude.

**Comment by victorhooi** [comment]
On latest Windows 2019 - termsrv.dll version is `10.0.17763.771` - there seems to be a fix for it here - https://github.com/stascorp/rdpwrap/issues/886. Is it hard to integrate that into your PR?

More generally, this would be amazing, if you are able to keep this project alive. It would be a shame to see all the previous work go to waste, if the project just died.

Has there been any recent activity from @binarymaster, or answer about giving others commit access?

Would forking this repository (and then remerging in future if binarymaster comes back) make sense?

**Comment by victorhooi** [comment]
Is it possible to add the rdpwrap.ini from here as well?

https://github.com/stascorp/rdpwrap/pull/922

**Comment by victorhooi** [comment]
If we find a rdpwrap.ini from other locations, how do we integrate it with this autoupdater?

Or how do we apply it locally?

**Comment by zzeroo** [comment]
@victorhooi see the **autoupdate.bat**. Look at the line `rdpwrap_ini_update_github_3=`

```batch
REM ***SNIP***
REM   tested by asmtron). The autoupdater will also use rdpwrap.ini files
REM   of other contributors like the one of "saurav-biswas".
REM   Extra rdpwrap.ini sources can also be defined...
REM
REM { Special thak to binarymaster, saurav-biswas and all other contributors }

REM -----------------------------------------
REM Location of new/updated rdpwrap.ini files
REM -----------------------------------------
set rdpwrap_ini_update_github_1="https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini"
set rdpwrap_ini_update_github_2="https://raw.githubusercontent.com/saurav-biswas/rdpwrap-1/patch-1/res/rdpwrap.ini"
REM set rdpwrap_ini_update_github_3="https://raw.githubusercontent.com/....Extra.3...."
REM set rdpwrap_ini_update_github_4="https://raw.githubusercontent.com/....Extra.4...."
REM ***SNAP***
```

**Comment by gerardoparedes** [comment]
I have 18362.592 it everything is in green but still only one connection allowed

**Comment by gerardoparedes** [comment]
I have 18362.592 it everything is in green but still only one connection allowed

image
image

**Comment by gerardoparedes** [comment]
image

**Comment by MarkosTech** [comment]
same

**Comment by jfariasf** [comment]
Have the same issue even with the 7e21baf commit. The program passes all checks but it doesn't work on 18362.592. Any current user will be required to disconnect.

Edit: It worked when the updater downloaded a DLL. I don't know the source of this file.

**Comment by hyj1991** [comment]
LGTM, thx :)

**Comment by Adeshwar03** [comment]
pls update if you can for 10.0.14393.3503

**Comment by AnDrEyKa-111** [comment]
@asmtron hi! I modified your autoupdate script: it now saves versions of termsrv.dll and remembers last supported version. So if dll is updated and new version is not supported, it replace new unsupported version from saved last supported one. And waiting, when support of new version is added. And when new version is get supported, it replace old supported version from saved new one. So the "server" will always be in multi-user RDP mode and run up-to-date dll as soon as it posible automaticly. I tested this modified script for some typical situations, it works fine, but i think it need more testing before share it for all. Is it interesting for you? How can i send it to you?

**Comment by asmtron** [comment]
Hi,
very good idea to store the current termsrv.dll and to use it as fall back on new windows updates ;)

The best way is if you upload (pull request) your modified autoupdate.bat to https://github.com/asmtron/rdpwrap/tree/master/bin and when it is ready, we can merge it with the original autoupdate.bat.

**Comment by AnDrEyKa-111** [comment]
[autoupdate.zip](https://github.com/stascorp/rdpwrap/files/4219533/autoupdate.zip)

> Hi,   very good idea to store the current termsrv.dll and to use it as fall back on new windows updates ;)   The best way is if you upload (pull request) your modified autoupdate.bat to https://github.com/asmtron/rdpwrap/tree/master/bin and when it is ready, we can merge it with the original autoupdate.bat.   thx,      

Here it is (in attachment). I'm newbie here, can't find how to pull request...

**Comment by mariagil1975** [comment]
Could you tell us a little tutorial on how to perform the complete installation with the new “autouodate”
I think that the first thing to do is install the RDPWInst-v1.6.2.msi
From here I have complicated with the updates. What I was doing was putting the rdpwrap_ini_updater and re-install in the% ProgramFiles% \ RDP Wrapper directory.
Then I unzip the files “autoupdate-v07.09.2019” in the same location and run “autoupdate__enable_autorun_on_startup.bat” and now I also add the file “autoupdate.bat” in the directory (I don't know if I have to execute it) What is the correct method?

**Comment by pelaooo** [comment]
I have the same question.  I don't know how to do the installation again and how to install the autoupdate.bat

**Comment by affinityv** [comment]
That updater is used AFTER the install, at any time.  It simply adds some extra sections to the INI file, based only on what the auto-updater cmd file knows about.  That won't get you all the possible combinations, but if the cmd file has knowledge about /your/ system, ala, it has the right ini section, then it will be good.  The cmd file will restart RDP, nothing more to do from what I can see.  But you must run the cmd file from an elevated cmd session (run as administrator).

EDIT: wrong....  I was talking about another auto updater; this one is bloody brilliant!

**Comment by pD1reNqSi** [comment]
> very good idea to store the current termsrv.dll and to use it as fall back on new windows updates ;)

And what about uploading the new unknown dll to some place in order to a developer analise and/or send a message about the new dll ?

**Comment by pelaooo** [comment]
Thanks affinityv.  Great contribution AnDrEyKa-111.  Thank you all for making all this possible.

**Comment by JDunn82** [comment]
Is there a way to make it so when the autoupdate is run it does not reset the windows firewall ports? for example mainly use 5589 for my RDP and after i run the autoupdate I need to run a bat file I made to open the port again in the windows firewall or I am unable to use the rdp. looked though the bats a bit but have no clue what may be triggering it to kill that off. 

thanks this has been quite the most viable tool for me with my day to day job!

**Comment by mariagil1975** [comment]
I still don't understand the update process.  I have installed Windows again and installed the RDP Wrapper Library file v1.6.2.  Then I don't know what I have to do to activate autoupdate since I have several Update files and I don't know which files are valid for autoupdate.  Are these files valid?  rdpwrap_ini_updater and autoupdate-v07.09.2019

**Comment by mariagil1975** [comment]
I think that all people have the same doubt because nobody knows the answer

**Comment by AnDrEyKa-111** [comment]
> I think that all people have the same doubt because nobody knows the answer

All answers are in first post in this thread by Asmtron

**Comment by pelaooo** [comment]
María. In spanish for you.
NO use otra ubicación para instalar / extraer los archivos RDP Wrapper.
    USE SOLO el directorio "% ProgramFiles% \ RDP Wrapper" (normalmente C: \ Program Files \ RDP Wrapper)


 2. Copie los archivos / carpetas del archivo "autoupdate-v07.09.2019.zip" (o más reciente) en el directorio "% ProgramFiles% \ RDP Wrapper"


 3. Para habilitar la ejecución automática de autoupdate.bat en el inicio del sistema, ejecute el archivo por lotes del asistente de seguimiento como administrador:

    "% ProgramFiles% \ RDP Wrapper \ helper \ autoupdate__enable_autorun_on_startup.bat"


 4. Establezca en su Antivirus / WindowsDefnder una exclusión en la carpeta "% ProgramFiles% \ RDP Wrapper" para evitar la eliminación de archivos RDP Wrapper


 5. Ahora puede usar el archivo por lotes de actualización automática para instalar y actualizar el RDP Wrapper. Ejecute el siguiente archivo por lotes de actualización automática como administrador:

   "% ProgramFiles% \ RDP Wrapper \ autoupdate.bat"

NOTA: Usa el autoupdate de AnDrEyKa-111.

**Comment by jonvickers** [comment]
def working on Win 10 Pro 1909 Term Srv 10.0.18362.657.   Thank you!

**Comment by bxjxxyy** [comment]
My system is useing termsrv.dll version : 10.0.18362.657 
So I copied  rdpwrap.ini and replace mine.
Then I got this problem:
image
image
Everything is correct,but I still can't login.Tried restart computer

**Comment by fragtion** [comment]
10.0.17763.771 ?

**Comment by Paramofidar** [comment]
Can Anyone Help For Windows 10 2004 

win2004

**Comment by Paramofidar** [comment]
Updated File With New Details But Problem is there as per photo bellow
rdpwrap1

**Comment by pepepl** [comment]
Uncheck "Single session per user"

**Comment by Paramofidar** [comment]
Below Link Worked Perfectly without any special efforts... Special Thanks to @asmteon and All Team Members

https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

with Win10 2004 or may 2020 update

**Comment by jwaschkau** [comment]
@asmtron Works for me with Win May 2020 update. Thanks for your work.

**Comment by asmtron** [comment]
new pull request: https://github.com/stascorp/rdpwrap/pull/1160

**Comment by gitgotgone** [comment]
Is this still being updated/maintained? In the bat file, there are two sources of updated ini files. The second one is 
https://raw.githubusercontent.com/saurav-biswas/rdpwrap-1/patch-1/res/rdpwrap.ini
This one hasn't been updated since 2019.
The first one, referencing the personal @asmtron repository, is 
https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini
But that file has a header that says:
Updated=2021-10-07
Which is 2 weeks into the future...
I assume this is a typo, and it is supposed to be 2021-07-10, which is 2 months ago. There has been a major Windows update since then, e.g. Win 10 OS build 19042.1237.

**Comment by affinityv** [comment]
There is mine too [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini), it gets updated regularly.  I mostly rely upon @sebaxakerhtc to create the correct x64 section.  Most people use x64, but some need x86.  Whenever there is a new version, then both termsrv.dll files need to be uploaded here so that the settings can be worked out.

**Comment by gitgotgone** [comment]
Ah--I was using an old version of the autoupdater. I see now there are a bunch of new sources, including yours, @affinityv !
set rdpwrap_ini_update_github_1="https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini"
set rdpwrap_ini_update_github_2="https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini"
set rdpwrap_ini_update_github_3="https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini"
set rdpwrap_ini_update_github_4="https://raw.githubusercontent.com/DrDrrae/rdpwrap/master/res/rdpwrap.ini"
set rdpwrap_ini_update_github_5="https://raw.githubusercontent.com/saurav-biswas/rdpwrap-1/master/res/rdpwrap.ini"

Does the newest version you got from @sebaxakerhtc work with 19042.1237 (Win 10 Pro x64 v20H2)? I don't see it listed in any of the above ini. I only see a lot of .1000 versions, which I think are windows preview versions.

@affinityv , please see:
https://github.com/stascorp/rdpwrap/issues/1520
for an ini that does work with 1237. Maybe post it? Thanks!

**Comment by affinityv** [comment]
> Does the newest version you got from @sebaxakerhtc work with 19042.1237 (Win 10 Pro x64 v20H2)? I don't see it listed in any of the above ini. I only see a lot of .1000 versions, which I think are windows preview versions.

Yes, it is a 1202 ... it's the termsrv.dll version that counts, not the Windows 10 version.

**Comment by gitgotgone** [comment]
Excellent--duh, thanks for explaining!

**Comment by gjuecat** [comment]
does anybody have an update for 21H2 19044.1288? this version is not supported at the moment

**Comment by affinityv** [comment]
> does anybody have an update for 21H2 19044.1288? this version is not supported at the moment

What is the termsrv.dll version?

**Comment by gjuecat** [comment]
termsrv.dll Version 10.0.19041.1348

**Comment by Paramofidar** [comment]
Thanks Working Finely.

**Comment by affinityv** [comment]
> termsrv.dll Version 10.0.19041.1348

That one is certainly covered in my [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini)

**Pull request closed without merging**
