### PR TITLE
Update rdpwrap.ini (10.0.18362.267, 10.0.18362.53 ...)

### PR DESCRIPTION
**Pull request by asmtron**
add support for:
10.0.18362.267
10.0.18362.53
10.0.18362.1
10.0.17763.437
10.0.17763.379
10.0.17763.292
10.0.17763.165 x64
10.0.17134.706

https://github.com/stascorp/rdpwrap/issues/795#issue-448382061

### CODE REVIEW

**Comment by breentcb** [comment]
Could you add support for Win10 1903; Build 18362.175 as wrapper does not work with this version of the any file.

**Comment by asmtron** [comment]
@breentcb
"Win10 1903; Build 18362.175" is also supported (it use termsrv.dll 10.0.18362.53)

**Comment by breentcb** [comment]
I can only get to work using the checker.  Config file is all green fully supported.  I have uninstalled and reinstalled the files and updated the ini file.  When I run Remote Desktop I get 
image

**Comment by jtomasrl** [comment]
working fine on 10.0.17763.437

**Comment by ghostrat26** [comment]
Not working @ Win10 1903 18362.207
Can please help on that? Thanks.

**Comment by marcosfrm** [comment]
Be aware that if you download rdpwrap.ini from @asmtron's commit ( ... -> View file -> Raw) you need to convert line endings from Unix (LF) to Windows (CR LF)!

**Comment by meifazhuce** [comment]
Not working @ Win10 1803 17134.885
Can please help on that? Thanks.

**Comment by Benjamin-Loison** [comment]
@meifazhuce 

Same problem, could someone send a txt with things to add in the conf file please ?

**Comment by scalpelx** [comment]
10.0.18362.267 not worked. Could you add support for that version? Thanks.

**Comment by webmylife** [comment]
#851

**Comment by webmylife** [comment]
This has solved the problem described in #851

**Pull request closed without merging**
